image:
  repository: gitlabregistry.innoq.com/innoq/praktika/todoapp
  tag: latest
  pullSecret: s4-gitlab-registry

env:
  - { name: DATABASE_URL, value: "jdbc:postgresql://todoapp-db.cffrlivljgmr.eu-central-1.rds.amazonaws.com:5432/todoapp" }
  - { name: DATABASE_USERNAME, value: "todoapp" }
  - { name: DATABASE_PASSWORD, valueFrom: { secretKeyRef: { name: credentials, key: DATABASE_PASSWORD }}}

owner: torsten.mandry@innoq.com
gitRepo: https://gitlab.innoq.com/innoq/praktika/todoapp
port: 8080
healthPath: /health
initialHealthCheckDelay: 2
replicaCount: 1
secureBackend: false

#restrictAccess:
#  allowGroups:
#    - Mitarbeiter

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi

ingress:
  dns: todoapp.apps.innoq.io